### ISSUE TITLE
Upgrade Node12 to Node16

### ISSUE THREAD

**Issue by jagadeeshdelhivery** [1arp/create-a-file-action#1]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: 1arp/create-a-file-action@0.2

**Comment by tueda** [comment]
FYI: There is a fork with Node16: https://github.com/fertrig/create-file-action

**Comment by 1arp** [comment]
I have upgraded the dependency to node 20 with the latest v0.3.
Closing the issue
