### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by aryairani** [1arp/create-a-file-action#4]
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Here is a warning I get when using `1arp/create-a-file-action@0.4.4`. How much time do we have? 😬

**Comment by 1arp** [comment]
Hmm, surprising. I'll try to reproduce it and fix it over the weekend ( end of the month ).
Thanks for creating the issue 😄

**Comment by 1arp** [comment]
I am sorry I am not able to reproduce the issue. Where exactly are you seeing this warning ? 
Can you please share the steps to reproduce it ?

Also I am not using the mentioned `set-ouput` command anywhere in the implementation.

I have attached my run of the Github action.
<img width="886" alt="Screenshot 2024-04-01 at 00 18 19" src="https://github.com/1arp/create-a-file-action/assets/42278019/9022aa39-258e-4ae8-967d-d4dd78723ceb">

**Comment by aryairani** [comment]
Sorry @1arp, I see I reported the issue to the wrong repo / wrong plugin. Disregard! Sorry again.

**Comment by 1arp** [comment]
np!
